# typed: false
# frozen_string_literal: true

# Homebrew formula for mrl - ModelRelay CLI
# Auto-generated by scripts/update-homebrew-formula.sh
# Version: 0.1.0

class Mrl < Formula
  desc "ModelRelay CLI for running and testing AI agents"
  homepage "https://modelrelay.ai"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/modelrelay/modelrelay/releases/download/mrl-v#{version}/mrl-#{version}-darwin-arm64.tar.gz"
      sha256 "617e871cd5c9f564ace55bd4ce4a964ee58132d2b4cfc512cddf63208b953f8e"

      def install
        bin.install "mrl-darwin-arm64" => "mrl"
      end
    end

    on_intel do
      url "https://github.com/modelrelay/modelrelay/releases/download/mrl-v#{version}/mrl-#{version}-darwin-amd64.tar.gz"
      sha256 "151cafcd114903162f44a52126b0a87e6165e8d72337897d5f03af0ffd6a098a"

      def install
        bin.install "mrl-darwin-amd64" => "mrl"
      end
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/modelrelay/modelrelay/releases/download/mrl-v#{version}/mrl-#{version}-linux-arm64.tar.gz"
      sha256 "c12c93d893c881a45429b2c1a285acdf954461d323d900866c1e0106f0d22959"

      def install
        bin.install "mrl-linux-arm64" => "mrl"
      end
    end

    on_intel do
      url "https://github.com/modelrelay/modelrelay/releases/download/mrl-v#{version}/mrl-#{version}-linux-amd64.tar.gz"
      sha256 "2c7da4d9083f2c16bc7e8bf91831a6184f15ebd04e9db0c94482f54ce27e8ff1"

      def install
        bin.install "mrl-linux-amd64" => "mrl"
      end
    end
  end

  test do
    assert_match "ModelRelay CLI", shell_output("#{bin}/mrl --help")
  end
end
